### PR TITLE
Fixed Spacing, new example, more rules

### PR DESCRIPTION
**Pull request by Lodobo**
# Modifications
- Changed main file to copy the example provided by PURDUE OWL
- Fixed spacing between paragraph groups, between headers, and for titles by adding rules for block elements.
- mla9 discourages the use of paragraph justification, so I set paragraph justification to false.
- Added 0.5 inch spacing for the header
- Merged template.typ and mla9.typ
- Removed duplicate bibliography sections. Now it's only in template.typ.
- Added document metadata
- Added configuration for table figures
- TODO: remove comma between author and page number inside in-line citations.
- TODO: add configuration for image figures

### CODE REVIEW

**Comment by mketab** [comment]
Tested and used this PR for an actual assignment, works great. the only problem is that when you're importing the "Template.typ" file you imported it lowercase causing errors.

**Comment by wychwitch** [comment]
WOAH this is fantastic work, thank you so much for the PR!! Would you like it to be merged now or wait until the TODOs are finished? @Lodobo

**Comment by Lodobo** [comment]
> Tested and used this PR for an actual assignment, works great. the only problem is that when you're importing the "Template.typ" file you imported it lowercase causing errors.

@mketab Thanks, I was hesitating between lower-case filenames and title case, and the result is as you have seen.

> WOAH this is fantastic work, thank you so much for the PR!! Would you like it to be merged now or wait until the TODOs are finished?

@wychwitch I've added some new commit to add show rules for illustrations, when doing so I noticed the numbering of tables wouldn't increment as expected, so I fixed that at the same time. I don't mind if you change the contents of example.typ to something simpler, actually, it might be a good idea since I just stole the example provided by Purdue OWL for testing purposes. You can merge it now if you want, I don't know how to fix the comma problem inside in-line citations.

**Comment by wychwitch** [comment]
many thanks again!! I'll consider the simpler example but I think having the perdue example is great to compare against ^^ The commas thing might just be something that's worked out as Typst is further developed, but it might be a good idea to open an issue on their repo eventually

**Pull request merged**
